//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Gubaidullin.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Exams = new HashSet<Exams>();
        }
    
        public int ID_Employee { get; set; }
        public string Cipher { get; set; }
        public string Surname { get; set; }
        public string Position { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Chief { get; set; }
    
        public virtual DepartmentHeads DepartmentHeads { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Educators Educators { get; set; }
        public virtual Engineers Engineers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exams> Exams { get; set; }
    }
}
