//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Gubaidullin.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineers
    {
        public int ID_Engineer { get; set; }
        public string EngineerType { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
