//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Gubaidullin.ModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPEntities : DbContext
    {
        public UPEntities()
            : base("name=UPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmentHeads> DepartmentHeads { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Disciplines> Disciplines { get; set; }
        public virtual DbSet<Educators> Educators { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Engineers> Engineers { get; set; }
        public virtual DbSet<Exams> Exams { get; set; }
        public virtual DbSet<Faculties> Faculties { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
