//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Gubaidullin.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID_Request { get; set; }
        public Nullable<int> ID_Discipline { get; set; }
        public string ID_Specialty { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
